spring:
  application:
    name: graphql_example
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:cuenta-db
  h2:
    console:
      enabled: true
  graphql:
    graphiql:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081